# Generated by Django 5.0.7 on 2024-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_proof_job_alter_proof_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='status',
            field=models.CharField(choices=[('no-status', 'No Status'), ('approved', 'Approved'), ('declined', 'Declined')], default='no-status', max_length=20),
        ),
    ]
